In [6]:
import gym
import gym_sokoban
import time
import datetime as dt
import matplotlib.pyplot as plt
import math
from collections import deque
import random
import numpy as np
import pickle
import sys
import tqdm
import os
from collections import namedtuple,defaultdict,deque 

In [7]:
chapter = 0
level = 0


env_name = 'Sokoban-v1'
env = gym.make(env_name)
ACTION_LOOKUP = env.unwrapped.get_action_lookup()
env.unwrapped.set_level(chapter,level)
env.seed(0)
env.reset()
print("Created environment: {}".format(env_name))


#create Results/Chapter [chapter]/Level [level] folder
if not os.path.exists('Results/Chapter '+str(chapter)+'/Level '+str(level)):
    os.makedirs('Results/Chapter '+str(chapter)+'/Level '+str(level))

Created environment: Sokoban-v1


In [8]:
_ = env.reset()

In [23]:
env.render()

True

In [33]:
def map(x,  in_min,  in_max,  out_min,  out_max) :
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;

def greedy_policy(V,s,eps_comp=1e-8):
    #.9 prob of greedy action
    #.1 prob of random action

    if s not in V:
        V[s] = np.zeros(env.action_space.n)
    r_choice = 1 -map(eps_comp,0,1,0.1,.6)
    if np.random.random() < r_choice:
        return np.random.choice(np.arange(env.action_space.n))
    else:
        max_val = np.max(V[s])
         #find all actions that have the max value and choose one at random
        max_actions = np.argwhere(V[s] == max_val).flatten()
        return np.random.choice(max_actions)
def mod_P(P,state,action,next_state,reward):
    if state not in P:
        P[state] = {}
    if action not in P[state]:
        P[state][action] = [next_state,0,reward]
    else:
        P[state][action][0] = next_state
        P[state][action][2] = reward
    min_rw = 999999999999
    _tmp = [_r for _s,_a,_r in P[state].values()]
    _tmp = np.array(_tmp)
    #make sure all rewards are positive and sum to 1
    _tmp = _tmp - np.min(_tmp)
    _tmp = _tmp/np.sum(_tmp)
    
    for _i,_t in enumerate(P[state]):
        P[state][_t][1] = _tmp[_i]
    


In [34]:
EVERY_VISIT_MC = False
EPISODES = 100
V = {}
total_returns = {}
N = {}
P = {}
pbar = tqdm.tqdm(range(EPISODES),)
finished = 0
max_reward = 0
for episode in pbar:
    
    visited = []
    env.reset()
    state = env.unwrapped.serialize_state()
    done = False
    last_reward = 0
    for t in range(220):
        action_time = time.time()
        if done:
            break
        action = greedy_policy(V,state,eps_comp=episode/EPISODES)
        next_state, reward, done, info = env.step(action)
        if done and t < 159:
            finished += 1
        if reward > max_reward:
            max_reward = reward
       
        if EVERY_VISIT_MC or (not EVERY_VISIT_MC and state not in visited):
            if not EVERY_VISIT_MC:
                visited.append((state,action))
            if state not in total_returns:
                total_returns[state] = np.zeros(env.action_space.n)
            if state not in N:
                N[state] = np.zeros(env.action_space.n)
            for _state,_action in visited:
                total_returns[_state][_action] += reward
                N[_state][_action] += 1
                V[_state][_action] = (total_returns[_state][_action] / N[_state][_action])
                mod_P(P,state,action,next_state,(total_returns[_state][_action] / N[_state][_action]))
            
            
            #V[state][action] = (total_returns[state][action] / N[state][action])
        state = env.unwrapped.serialize_state()
        last_reward = reward
    pbar.set_description(f'Training MC, finished={finished};Max reward gained={round(max_reward,3)}')
    if episode % 1000 == 0:
        fname = 'Results/Chapter '+str(chapter)+'/Level '+str(level)+'/MC_'+('every' if EVERY_VISIT_MC else 'first')+'_'+str(EPISODES)+'_episodes_temp.bin'
        with open(fname, 'wb') as handle:
            pickle.dump(V, handle, protocol=pickle.HIGHEST_PROTOCOL)
        with open('Results/Chapter '+str(chapter)+'/Level '+str(level)+'/P_'+('every' if EVERY_VISIT_MC else 'first')+'_'+str(EPISODES)+'_episodes_temp.bin', 'wb') as handle:
            pickle.dump(P, handle, protocol=pickle.HIGHEST_PROTOCOL)


            
#save the value function
fname = 'Results/Chapter '+str(chapter)+'/Level '+str(level)+'/MC_'+('every' if EVERY_VISIT_MC else 'first')+'_'+str(EPISODES)+'_episodes.bin'
with open(fname, 'wb') as handle:
    pickle.dump(V, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('Results/Chapter '+str(chapter)+'/Level '+str(level)+'/P_'+('every' if EVERY_VISIT_MC else 'first')+'_'+str(EPISODES)+'_episodes.bin', 'wb') as handle:
            pickle.dump(P, handle, protocol=pickle.HIGHEST_PROTOCOL)
    

  0%|          | 0/100 [00:00<?, ?it/s]C:\Users\duong\AppData\Local\Temp\ipykernel_39220\2206912566.py:31: RuntimeWarning: invalid value encountered in divide
  _tmp = _tmp/np.sum(_tmp)
Training MC, finished=69;Max reward gained=35.886: 100%|██████████| 100/100 [00:34<00:00,  2.88it/s]


In [7]:
fname = 'Results/Chapter '+str(chapter)+'/Level '+str(level)+'/MC_'+('every' if EVERY_VISIT_MC else 'first')+'_'+str(EPISODES)+'_episodes.bin'
with open(fname, 'wb') as handle:
    pickle.dump(V, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [5]:

for s in V:
    argmax = np.argmax(V[s])
    max_val = np.max(V[s])
    s = s[26:40] +'\n'+ s[26+26:40+26]
    print("{} Action: {} Value: {}".format(s,ACTION_LOOKUP[argmax],max_val))

37001000000833
30000700730553 Action: down Value: 11.434698421379244
37000000000833
30001700730553 Action: extinguish Value: 13.77710830503389
37000100000833
30000700730553 Action: left Value: 9.458390044858819
37000000000833
30000100730553 Action: down Value: 13.555995520004384
37000100000833
30000000730553 Action: extinguish Value: 12.427316269733907
37001000000833
30000000730553 Action: right Value: 9.330905605004048
37010000000833
30000000730553 Action: down Value: 10.360924743592541
37000000000833
30010000730553 Action: down Value: 14.625099661574152
37000000000833
30000000730553 Action: extinguish Value: 15.600341616742327
37000000000833
30000000730553 Action: extinguish Value: 16.688919597037355
37000000000833
30010000730553 Action: up Value: 16.74839334231231
37000000000833
30000000730553 Action: up Value: 18.169342083298574
37000000000833
30000000730553 Action: up Value: 15.280572583334617
37000000000833
30000000730553 Action: right Value: 9.865080823396372
37000000000833
3000

In [3]:
#load the value function

fname = "D:\\2023-2024\\RNN\\Sokoban\\Results\\Chapter 0\\Level 3\\MC_first_100000_episodes_ok.bin"
with open(fname, 'rb') as handle:
    V = pickle.load(handle)

In [23]:
def greedy_policy_pi(V,s):
    #.9 prob of greedy action
    #.1 prob of random action

    if s not in V:
        V[s] = np.zeros(env.action_space.n)
    r_choice = .2
    if np.random.random() < r_choice:
        return np.random.choice(np.arange(env.action_space.n))
    else:
        max_val = np.max(V[s])
         #find all actions that have the max value and choose one at random
        max_actions = np.argwhere(V[s] == max_val).flatten()
        return np.random.choice(max_actions)


In [24]:

for i in range(1000):
    time.sleep(1)
    _ = env.reset()
    state = env.unwrapped.serialize_state()
    st_time = time.time()
    done = False
    t= 0
    last_reward = 0
    last_time = time.time()
    last_state = state
    rendered_frame = 0
    while True:
        if time.time() - st_time < .2:
            env.render()
            rendered_frame += 1
            time.sleep(1/144)
            if (time.time() - last_time) > 1:
                print(f'\rFPS: {rendered_frame}',end='')
                rendered_frame = 0
                last_time = time.time()
            continue
        st_time = time.time()
        action_time = time.time()
        action = greedy_policy_pi(V,state)
        
        state, reward, done, info = env.step(action)
        state = env.unwrapped.serialize_state()
        #print(f'{ACTION_LOOKUP[action]} state change: {last_state != state}',end=' ')
        last_state = state
        last_reward = reward
        t += 1
        if done or t > 150:
            env.render()
            break
        env.render()

FPS: 30

KeyboardInterrupt: 

In [32]:
ACTION_LOOKUP

{0: 'right', 1: 'up', 2: 'down', 3: 'left', 4: 'extinguish'}

In [10]:
_ = env.reset()
state = env.unwrapped.serialize_state()


In [13]:

action = 1
next_state, reward, done, info = env.step(action)
env.render()
print("Action: {} Reward: {}".format(ACTION_LOOKUP[action],reward))

Action: up Reward: 7.8469999999999995


In [14]:
for v in V.values():
    print(np.round(v,2))

[13.06 13.11 13.14 15.45 13.19]
[13.13 13.78 13.78 16.39 13.75]
[13.92 14.94 14.92 17.77 15.  ]
[15.66 16.48 20.2  15.84  8.77]
[16.43 15.2  15.18 14.73  8.71]
[16.66 14.86 15.69 14.84  8.73]
[15.43 15.99 16.03 15.27 17.58]
[15.11 15.04 15.05 15.97 15.7 ]
[18.97 20.92 18.92 18.35  9.78]
[21.81 19.99 19.1  19.03  9.79]
[17.18 19.2  17.06 17.37  9.72]
[20.15 18.32 17.26 18.26  9.73]
[22.62 21.   20.95 19.99  9.78]
[22.21 21.9  21.85 21.15 23.5 ]
[23.86 22.78 23.79 22.15 14.76]
[23.24 23.21 23.25 22.77 24.43]
[16.62 16.99 18.1  16.68 16.99]
[16.15 16.28 16.12 16.94 16.12]
[17.76 17.09 18.93 17.71 17.75]
[17.02 16.19 16.21 16.42 16.18]
[17.08 14.02 14.88 14.51  8.71]
[18.59 19.38 18.57 18.59 14.55]
[21.31 21.23 21.2  21.13 23.14]
[19.09 18.65 18.65 19.1  20.15]
[19.22 18.45 18.93 17.65 14.5 ]
[22.49 20.82 21.08 19.9  14.65]
[19.81 18.24 17.   17.31 14.52]
[18.22 16.17 16.19 16.27 14.47]
[16.03 15.92 17.42 15.52 15.71]
[16.97 17.93 16.72 16.48 14.47]
[14.87 14.71 15.95 14.58 14.79]
[16.23 1